global:
  project_dir: !ENV ${OWID_COVID_PROJECT_DIR}
  credentials: !ENV ${OWID_COVID_VAX_CREDENTIALS_FILE}
pipeline:
  get-data:
    parallel: True
    countries:
    njobs: -2
    skip_countries:
      - Gabon
      - North Macedonia
      - Northern Cyprus
      - Philippines
      - South Africa
  process-data:
    skip_complete:
      - Pitcairn
    skip_monotonic_check:
    skip_anomaly_check:
      Australia:
        - date: 2021-05-24
          metrics: people_vaccinated
      Bahrain:
        - date: 2021-03-06
          metrics: total_vaccinations
      Bolivia:
        - date: 2021-03-06
          metrics: people_vaccinated
      Brazil:
        - date: 2021-01-21
          metrics: 
           - total_vaccinations
           - people_vaccinated
      Nigeria:
        - date: 2021-06-15
          metrics: people_fully_vaccinated
  generate-dataset:
